apiVersion: apps/v1
kind: Deployment
metadata:
  name: flume-test-agent
  labels:
    app: flume
    chart: flume-0.1.0
    release: flume-test
    heritage: Helm
spec:
  replicas: 1
  selector:
      matchLabels:
          app: flume
          release: flume-test
  template:
    metadata:
      labels:
        app: flume
        release: flume-test
    spec:
      containers:
        - name: flume
          command: [
                    "/bin/bash",
                    "-c",
                    "${FLUME_HOME}/bin/flume-ng agent -n a1 -c conf -f ${FLUME_HOME}/conf/agent.conf -Dflume.root.logger=INFO,console -Dflume.monitoring.type=http -Dflume.monitoring.port=44123"
                    ]
          image: "liupengfei99/flume:1.9.0"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 44123
          volumeMounts:
          - name: flume-config
            mountPath: /opt/apache-flume/conf/agent.conf
            subPath: agent.conf
          - name: flume-config
            mountPath: /opt/apache-flume/conf/core-site.xml
            subPath: core-site.xml
      volumes:
      - name: flume-config
        configMap:
          name: flume-config
      - name: flume-data-volume
        persistentVolumeClaim:
          claimName: flume-data-claim
---
# this volume claim is added in case of the given flume agent uses the file channel
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flume-data-claim
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 8Gi
# used to bind PV with the same class name, if you want the DefaultStorageClass create a PV dynamically, just put "".
  storageClassName: rook-ceph-block

