apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-flume-cm
data:
  core-site.xml: |-
    <configuration>
    <property>
      <name>fs.s3a.connection.ssl.enabled</name>
      <value>true</value>
      <description>Enables or disables SSL connections to S3.</description>
    </property>

    <property>
      <name>fs.s3a.endpoint</name>
      <description>AWS S3 endpoint to connect to. An up-to-date list is
        provided in the AWS Documentation: regions and endpoints. Without this
        property, the standard region (s3.amazonaws.com) is assumed.
      </description>
      <value>minio.lab.sspcloud.fr</value>
    </property>

    <property>
      <name>fs.s3a.path.style.access</name>
      <value>true</value>
      <description>Enable S3 path style access ie disabling the default virtual hosting behaviour.
        Useful for S3A-compliant storage providers as it removes the need to set up DNS for virtual hosting.
      </description>
    </property>

    <property>
      <name>fs.s3a.aws.credentials.provider</name>
      <value>org.apache.hadoop.fs.s3a.TemporaryAWSCredentialsProvider</value>
    </property>

    <property>
      <name>fs.s3a.access.key</name>
      <value>{{ .Values.flumeApp.s3.accessKey }}</value>
    </property>

    <property>
      <name>fs.s3a.secret.key</name>
      <value>{{ .Values.flumeApp.s3.secretKey }}</value>
     </property>

     <property>
      <name>fs.s3a.session.token</name>
      <value>{{ .Values.flumeApp.s3.sessionToken }}</value>
     </property>
     </configuration>

{{/* This file include mecanishm requires the inclueded file must be a .toml. so not intresting */}}
  {{- $files := .Files }}
  {{- range tuple "agent.conf" }}
  {{ . }} : |-
  {{ $files.Get . }}
  {{- end }}
