apiVersion: v1
kind: Service
metadata:
  name: {{ include "flume.fullname" . }}
  labels:
    {{- include "flume.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: flume
  selector:
    {{- include "flume.selectorLabels" . | nindent 4 }}
